services:
  # Um serviço web que executa a aplicação Flask
  - type: web
    name: conveniencia-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: conveniencia-db
          property: connectionString

databases:
  # Banco de dados PostgreSQL
  - name: conveniencia-db
    databaseName: conveniencia
    user: conveniencia_user
    plan: free
